module.exports = {
  apps: [
    {
      name: "sharaspot-api",
      cwd: "/root/SharaSpot-Outreach/server",
      script: "dist/index.js",
      instances: 1,
      autorestart: true,
      max_memory_restart: "500M",
      env_file: "/root/SharaSpot-Outreach/server/.env",
      error_file: "/var/log/sharaspot/api-error.log",
      out_file: "/var/log/sharaspot/api-out.log",
      merge_logs: true,
    },
    {
      name: "sharaspot-worker",
      cwd: "/root/SharaSpot-Outreach/server",
      script: "dist/worker/index.js",
      instances: 1,
      autorestart: true,
      max_memory_restart: "500M",
      env_file: "/root/SharaSpot-Outreach/server/.env",exec_mode: "fork", 
      error_file: "/var/log/sharaspot/worker-error.log",
      out_file: "/var/log/sharaspot/worker-out.log",
      merge_logs: true,
    },
    {
      name: "sharaspot-frontend",
      cwd: "/root/SharaSpot-Outreach/client",
      script: "npm",
      args: "start",
      instances: 1,
      autorestart: true,
      max_memory_restart: "1G",
      env_file: "/root/SharaSpot-Outreach/client/.env",
      error_file: "/var/log/sharaspot/frontend-error.log",
      out_file: "/var/log/sharaspot/frontend-out.log",
      merge_logs: true,
    },
  ],
};
